const AI1_MODEL = 'gpt-5-nano';
const AI2_MODEL = 'gpt-5.6-luna';

const VERSIONS = Object.freeze({
  engine: 'shadow-v2-7',
  ai1Contract: 'shadow-v2-ai1-4',
  ai1Prompt: 'shadow-v2-ai1-prompt-7',
  ai2Contract: 'shadow-v2-ai2-6',
  ai2Prompt: 'shadow-v2-ai2-prompt-10',
  render: 'shadow-v2-render-7',
});

const DEFAULT_LIMITS = Object.freeze({
  maxAlerts: 100,
  maxUsers: 25,
  maxCandidatesPerUser: 30,
  maxTotalCalls: 125,
  maxOfficialCharsPerAlert: 30000,
  maxPersonalPromptChars: 60000,
  maxSelected: 5,
});

const LIMIT_BOUNDS = Object.freeze({
  maxAlerts: [1, 500],
  maxUsers: [1, 250],
  maxCandidatesPerUser: [1, 100],
  maxTotalCalls: [1, 750],
  maxOfficialCharsPerAlert: [1000, 180000],
  maxPersonalPromptChars: [2000, 180000],
  maxSelected: [1, 5],
});

const RURAL_ORGANIZATIONS = Object.freeze([
  'ministerio de agricultura pesca y alimentacion',
  'ministerio de agricultura',
  'ministerio de agricultura alimentacion y medio ambiente',
  'secretaria general de agricultura y alimentacion',
  'secretaria general de recursos agrarios y seguridad alimentaria',
  'direccion general de producciones y mercados agrarios',
  'direccion general de sanidad de la produccion agroalimentaria y bienestar animal',
  'direccion general de desarrollo rural innovacion y formacion agroalimentaria',
  'direccion general de la industria alimentaria',
  'consejeria de agricultura',
  'consejeria de agricultura ganaderia y desarrollo rural',
  'consejeria de agricultura ganaderia y alimentacion',
  'consejeria de agricultura pesca agua y desarrollo rural',
  'consejeria de agricultura pesca y alimentacion',
  'consejeria de agricultura desarrollo rural poblacion y territorio',
  'consejeria de ganaderia',
  'consejeria de medio rural',
  'consejeria de desarrollo rural',
  'consejeria del medio rural y politica agraria',
  'consejeria de medio rural y cohesion territorial',
  'consejeria de medio rural y del mar',
  'consejeria de medio rural y alimentacion',
  'consejeria de desarrollo rural ganaderia pesca y alimentacion',
  'consejeria de desarrollo rural y sostenibilidad',
  'consejeria de desarrollo rural y recursos naturales',
  'consejeria de agua agricultura ganaderia y pesca',
  'consejeria de sector primario',
  'departamento de agricultura ganaderia y medio ambiente',
  'departamento de agricultura ganaderia y alimentacion',
  'departamento de accion climatica alimentacion y agenda rural',
  'departamento de desarrollo rural y medio ambiente',
  'departamento de alimentacion desarrollo rural agricultura y pesca',
  'departamento de promocion economica medio rural y equilibrio territorial',
  'viceconsejeria de sector primario',
  'viceconsejeria de agricultura ganaderia y pesca',
  'direccion general de agricultura',
  'direccion general de ganaderia',
  'direccion general de produccion agricola y ganadera',
  'direccion general de produccion agraria',
  'direccion general de politica agraria comunitaria',
  'direccion general de desarrollo rural',
  'direccion general de industrias agroalimentarias',
  'direccion general de industria agroalimentaria',
  'direccion general de calidad agroalimentaria',
  'direccion general de sanidad animal',
  'direccion general de sanidad vegetal',
  'direccion general de agricultura y ganaderia',
  'direccion general de montes y biodiversidad',
  'direccion general de gestion forestal',
  'direccion general del agua',
  'direccion general de montes',
  'fondo espanol de garantia agraria',
  'fega',
  'entidad estatal de seguros agrarios',
  'enesa',
  'agencia de informacion y control alimentarios',
  'aica',
  'agencia de gestion agraria y pesquera',
  'servicio regional de investigacion y desarrollo agroalimentario',
  'serida',
  'instituto tecnologico agrario de castilla y leon',
  'itacyl',
  'instituto murciano de investigacion y desarrollo agrario y medioambiental',
  'imida',
  'instituto valenciano de investigaciones agrarias',
  'ivia',
  'instituto de investigacion y tecnologia agroalimentarias',
  'irta',
  'instituto de investigacion y formacion agraria y pesquera',
  'ifapa',
  'centro de investigacion y tecnologia agroalimentaria de aragon',
  'cita aragon',
  'agencia gallega de la calidad alimentaria',
  'agacal',
  'instituto canario de investigaciones agrarias',
  'icia',
  'instituto madrileno de investigacion y desarrollo rural agrario y alimentario',
  'imidra',
  'neiker',
  'servicio de explotaciones agrarias',
  'servicio de ayudas agrarias',
  'servicio de sanidad animal',
  'servicio de sanidad vegetal',
  'servicio de desarrollo rural',
  'servicio de produccion agraria',
  'oficina comarcal agraria',
  'oficinas comarcales agrarias',
  'confederacion hidrografica',
  'sociedad mercantil estatal de infraestructuras agrarias',
  'seiasa',
  'direccion general de agricultura y desarrollo rural de la comision europea',
  'dg agri',
]);

const RURAL_TERMS_BY_TOPIC = Object.freeze({
  agricultura: [
    'agricultura', 'agricola', 'agricolas', 'agricultor', 'agricultora',
    'agricultores', 'agricultoras', 'agrario', 'agraria', 'agrarios', 'agrarias',
    'agropecuario', 'agropecuaria', 'actividad agraria', 'sector agrario',
    'produccion agraria', 'produccion agricola', 'explotacion agraria',
    'explotaciones agrarias', 'titular de explotacion agraria', 'productor agrario',
    'productora agraria', 'productor agricola', 'productora agricola',
    'agricultura ecologica', 'produccion ecologica', 'agricultura regenerativa',
    'agricultura de conservacion', 'agricultura de precision', 'agricultura integrada',
    'produccion integrada', 'agricultura sostenible', 'agricultura familiar',
    'pequena explotacion agraria', 'explotacion prioritaria', 'titularidad compartida',
    'joven agricultor', 'jovenes agricultores', 'nuevo agricultor',
    'incorporacion a la agricultura', 'modernizacion de explotaciones',
    'plan de mejora de explotaciones', 'asesoramiento agrario', 'asesoramiento agricola',
    'formacion agraria', 'capacitacion agraria', 'maquinaria agricola',
    'tractor agricola', 'tractores agricolas', 'registro oficial de maquinaria agricola',
    'roma agricola', 'cuaderno de explotacion', 'cuaderno digital de explotacion',
    'sistema de informacion de explotaciones agricolas', 'siex', 'regepa',
    'registro general de la produccion agricola',
  ],
  ganaderia: [
    'ganaderia', 'ganadero', 'ganadera', 'ganaderos', 'ganaderas', 'ganado',
    'cabana ganadera', 'cabanas ganaderas',
    'pecuario', 'pecuaria', 'pecuarios', 'pecuarias',
    'explotacion ganadera', 'explotaciones ganaderas', 'titular de explotacion ganadera',
    'produccion ganadera', 'productor ganadero', 'productora ganadera',
    'granja', 'granjas', 'granja extensiva', 'ganaderia extensiva', 'ganaderia intensiva',
    'pastoreo', 'pastoreo extensivo', 'carga ganadera', 'unidad ganadera mayor',
    'bovino', 'bovina', 'bovinos', 'bovinas', 'vacuno', 'ganado vacuno', 'ganado bovino',
    'vaca nodriza', 'vacas nodrizas',
    'ovino', 'ovina', 'ovinos', 'ovinas', 'ganado ovino',
    'rebano ganadero', 'rebanos ganaderos',
    'caprino', 'caprina', 'caprinos', 'caprinas', 'ganado caprino', 'ovino caprino',
    'porcino', 'porcina', 'porcinos', 'porcinas', 'ganado porcino',
    'cerdo iberico', 'porcino iberico',
    'avicola', 'avicultura', 'explotacion avicola', 'aves de corral',
    'gallina ponedora', 'gallinas ponedoras',
    'cunicultura', 'explotacion cunicola', 'equino', 'equinocultura',
    'ganado equino',
    'apicultura', 'apicola', 'apicultor', 'colmena', 'colmenas',
    'sector lacteo', 'ganaderia de leche', 'productor de leche', 'leche cruda',
    'registro general de explotaciones ganaderas', 'rega', 'codigo rega',
    'identificacion animal', 'trazabilidad animal', 'movimiento de ganado',
    'guia de origen y sanidad pecuaria', 'transporte de animales vivos',
    'bienestar animal', 'ordenacion de explotaciones ganaderas',
    'razas autoctonas', 'libro genealogico animal', 'programa de cria animal',
    'asociacion de criadores', 'centro de limpieza y desinfeccion de vehiculos',
  ],
  cultivos: [
    'cultivo', 'cultivos', 'siembra', 'siembras', 'tierras de cultivo', 'superficie cultivada',
    'cereal', 'cereales', 'trigo', 'cebada', 'avena', 'centeno', 'triticale',
    'maiz', 'arroz', 'sorgo', 'girasol', 'colza', 'oleaginosas', 'proteaginosas',
    'leguminosa', 'leguminosas', 'garbanzo', 'lenteja', 'judia seca',
    'forraje', 'forrajes', 'cultivo forrajero', 'alfalfa',
    'hortaliza', 'hortalizas', 'horticola', 'horticolas', 'hortofruticola',
    'huerta', 'invernadero agricola', 'frutal', 'frutales', 'fruticultura',
    'fruta de hueso', 'fruta de pepita', 'olivar', 'olivo', 'aceituna',
    'vinedo', 'viticultura', 'viticola', 'sector vitivinicola',
    'almendro', 'almendra', 'pistacho', 'avellano', 'nogal', 'frutos secos',
    'citricos', 'naranjo', 'mandarino', 'limonero', 'patata', 'remolacha azucarera',
    'algodon', 'tabaco', 'lupulo', 'tomate para industria', 'cultivo industrial',
    'cultivos industriales', 'plantas aromaticas', 'plantas medicinales',
    'floricultura', 'vivero agricola', 'viveros agricolas', 'material vegetal',
    'semilla certificada', 'semillas certificadas', 'patata de siembra',
    'planton', 'plantones', 'variedad vegetal', 'variedades vegetales',
    'recursos fitogeneticos', 'cosecha', 'campana agricola', 'rendimiento agricola',
  ],
  pac_y_desarrollo_rural: [
    'politica agraria comun', 'pac', 'plan estrategico de la pac', 'pepac',
    'fondo europeo agricola de garantia', 'feaga',
    'fondo europeo agricola de desarrollo rural', 'feader',
    'fondo espanol de garantia agraria', 'fega', 'organismo pagador',
    'solicitud unica', 'pago basico', 'ayuda basica a la renta',
    'ayuda redistributiva', 'ayuda asociada', 'ayudas asociadas',
    'eco regimen', 'ecorregimen', 'eco regimenes', 'ecorregimenes',
    'derechos de ayuda', 'derechos de pago', 'reserva nacional de derechos',
    'condicionalidad reforzada', 'condicionalidad social', 'bcam',
    'buenas condiciones agrarias y medioambientales', 'intervencion sectorial',
    'programa de desarrollo rural', 'desarrollo rural', 'medio rural',
    'leader rural', 'metodo leader', 'grupo de accion local', 'grupos de accion local',
    'estrategia de desarrollo local participativo', 'despoblacion rural',
    'emprendimiento rural', 'diversificacion rural', 'servicios basicos rurales',
  ],
  sanidad_animal: [
    'sanidad animal', 'zoosanitario', 'zoosanitaria', 'programa sanitario ganadero',
    'programa nacional de erradicacion', 'enfermedad animal', 'enfermedades animales',
    'sacrificio obligatorio', 'vaciado sanitario', 'vacio sanitario',
    'inmovilizacion de ganado', 'restriccion de movimientos ganaderos',
    'peste porcina africana', 'peste porcina clasica', 'lengua azul',
    'tuberculosis bovina', 'brucelosis', 'encefalopatia espongiforme bovina',
    'encefalopatia espongiforme transmisible', 'scrapie', 'tembladera ovina',
    'enfermedad hemorragica epizootica', 'influenza aviar', 'gripe aviar',
    'enfermedad de newcastle', 'salmonelosis aviar', 'fiebre aftosa',
    'dermatosis nodular contagiosa', 'viruela ovina', 'viruela caprina',
    'rabia animal', 'triquina', 'triquinosis', 'varroa', 'pequeno escarabajo de la colmena',
    'bioseguridad ganadera', 'medicamento veterinario', 'medicamentos veterinarios',
    'antibioticos veterinarios', 'prescripcion veterinaria', 'veterinario de explotacion',
    'sistema integral de gestion de explotaciones ganaderas', 'sigegan',
    'subproducto animal no destinado a consumo humano', 'sandach',
  ],
  sanidad_vegetal: [
    'sanidad vegetal', 'fitosanitario', 'fitosanitaria', 'producto fitosanitario',
    'productos fitosanitarios', 'registro de productos fitosanitarios', 'ropo',
    'carnet de aplicador de fitosanitarios', 'uso sostenible de fitosanitarios',
    'gestion integrada de plagas', 'plaga vegetal', 'organismo nocivo vegetal',
    'cuarentena vegetal', 'pasaporte fitosanitario', 'certificado fitosanitario',
    'xylella fastidiosa', 'fuego bacteriano', 'flavescencia dorada',
    'mildiu', 'mosca del olivo', 'mosca de la fruta', 'polilla del racimo',
    'nematodo de la madera del pino', 'procesionaria del pino',
    'tuta absoluta', 'trips parvispinus', 'teosinte', 'malas hierbas invasoras',
    'material de reproduccion vegetal', 'semillas y plantas de vivero',
  ],
  agua_y_regadio: [
    'regadio', 'regadios', 'riego agricola', 'riego localizado', 'riego por goteo',
    'modernizacion de regadios', 'transformacion en regadio', 'zona regable',
    'comunidad de regantes', 'comunidades de regantes', 'sindicato de riegos',
    'junta central de usuarios de aguas', 'infraestructura de riego',
    'infraestructuras de riego', 'acequia', 'acequias', 'canal de riego',
    'balsa de riego', 'embalse para riego', 'red de riego', 'turno de riego',
    'dotacion de riego', 'concesion de aguas para riego', 'aprovechamiento de aguas para riego',
    'aprovechamiento de aguas', 'aprovechamiento de aguas superficiales',
    'aguas superficiales para riego', 'dominio publico hidraulico', 'dominio hidraulico',
    'comisaria de aguas', 'cuenca hidrografica',
    'captacion de agua para riego', 'pozo agricola', 'sondeo agricola',
    'fertirrigacion', 'regante', 'regantes', 'sequia agraria',
  ],
  forestal: [
    'forestal', 'silvicultura', 'silvicola', 'explotacion forestal',
    'aprovechamiento forestal', 'gestion forestal', 'ordenacion de montes',
    'plan tecnico de gestion forestal', 'monte de utilidad publica',
    'montes de utilidad publica', 'catalogo de montes', 'repoblacion forestal',
    'restauracion forestal', 'tratamiento selvicola', 'clareo forestal',
    'poda forestal', 'resina', 'resinacion', 'corcho', 'saca de corcho',
    'dehesa', 'sistema adehesado', 'pastos arbolados', 'biomasa forestal',
    'prevencion de incendios forestales', 'incendio forestal',
    'cortafuegos', 'faja auxiliar forestal', 'quema de restos forestales',
  ],
  tierra_pastos_y_fiscalidad: [
    'concentracion parcelaria', 'reordenacion parcelaria', 'finca rustica',
    'fincas rusticas', 'arrendamiento rustico', 'suelo agrario', 'tierra agraria',
    'tierras agrarias', 'banco de tierras', 'banco de tierras agrarias',
    'parcela agricola', 'parcelas agricolas', 'recinto sigpac', 'sigpac',
    'coeficiente de admisibilidad de pastos', 'pasto permanente', 'pastos permanentes',
    'pastos comunales', 'aprovechamiento de pastos', 'derechos de pasto',
    'via pecuaria', 'vias pecuarias', 'canada real', 'cordel pecuario',
    'vereda pecuaria', 'camino rural', 'caminos rurales',
    'fiscalidad agraria', 'fiscalidad agricola', 'modulos agrarios',
    'estimacion objetiva agraria', 'gasoleo agricola', 'devolucion del gasoleo agricola',
    'impuesto sobre bienes inmuebles rusticos', 'ibi rustico',
  ],
  clima_seguros_y_medio: [
    'seguro agrario', 'seguros agrarios', 'plan de seguros agrarios combinados',
    'agroseguro', 'enesa', 'siniestro agrario', 'peritacion agraria',
    'dano en cultivo', 'danos en cultivos', 'dano agrario', 'danos agrarios',
    'helada en cultivos', 'pedrisco en cultivos', 'granizo en cultivos',
    'inundacion de explotaciones agrarias', 'sequia en explotaciones agrarias',
    'adversidad climatica agraria', 'fenomeno climatico adverso agrario',
    'fertilizante', 'fertilizantes', 'producto fertilizante', 'plan de abonado',
    'abonado nitrogenado', 'estiercol', 'purin', 'purines', 'gestion de deyecciones ganaderas',
    'zona vulnerable a nitratos', 'contaminacion por nitratos agrarios',
    'cubierta vegetal en cultivos', 'erosion del suelo agricola',
    'practica agroambiental', 'medida agroambiental', 'agricultura baja en carbono',
    'sumidero de carbono agricola', 'huella de carbono de explotaciones agrarias',
  ],
  agroalimentacion_y_calidad: [
    'agroalimentario', 'agroalimentaria', 'industria agroalimentaria',
    'industria alimentaria', 'transformacion agroalimentaria', 'empresa agroalimentaria',
    'cooperativa agraria', 'cooperativas agrarias', 'cooperativa agroalimentaria',
    'sociedad agraria de transformacion', 'organizacion de productores agrarios',
    'organizacion de productores de frutas y hortalizas', 'opfh',
    'agrupacion de productores agrarios', 'cadena alimentaria',
    'ley de la cadena alimentaria', 'contrato alimentario', 'coste efectivo de produccion agraria',
    'precio agrario', 'precios agrarios', 'lonja agraria', 'lonja agropecuaria',
    'observatorio de precios agrarios', 'calidad agroalimentaria',
    'calidad diferenciada', 'denominacion de origen protegida',
    'indicacion geografica protegida', 'especialidad tradicional garantizada',
    'dop agroalimentaria', 'igp agroalimentaria', 'consejo regulador agroalimentario',
    'produccion ecologica certificada', 'operador ecologico', 'artesania alimentaria',
    'venta directa de productos agrarios', 'canal corto de comercializacion',
    'mercado local de productores', 'matadero', 'sala de despiece',
    'centro de recogida de leche', 'higiene de la produccion primaria',
  ],
  tramites_y_registros_rurales: [
    'registro de explotaciones agrarias', 'registro agrario',
    'registro de explotaciones ganaderas', 'registro viticola', 'registro de vinedo',
    'autorizacion de plantacion de vinedo', 'replantacion de vinedo',
    'arranque de vinedo', 'declaracion de cosecha', 'declaracion de produccion vitivinicola',
    'declaracion de existencias vitivinicolas', 'declaracion obligatoria de leche',
    'declaracion de entregas de leche', 'declaracion censal agraria',
    'inspeccion agraria', 'control de la pac', 'monitorizacion de parcelas agricolas',
    'quema de restos agricolas', 'quema agricola', 'eliminacion de restos vegetales',
    'licencia de actividad ganadera', 'autorizacion de explotacion ganadera',
    'plan sanitario integral de explotacion', 'plan de gestion de estiercoles',
    'plan de gestion de purines', 'contrato de integracion ganadera',
  ],
  fauna_y_entorno_productivo: [
    'caza', 'actividad cinegetica', 'aprovechamiento cinegetico',
    'gestion cinegetica', 'area privada de caza', 'areas privadas de caza',
    'coto de caza', 'cotos de caza',
    'dano de fauna en cultivos', 'danos de fauna en cultivos',
    'dano de fauna al ganado', 'danos de fauna al ganado',
    'ataque de lobo al ganado', 'ataques de lobo al ganado',
    'dano de oso al ganado', 'dano de jabalies en cultivos',
    'dano de conejo en cultivos', 'prevencion de danos de fauna',
    'gestion cinegetica compatible con agricultura', 'cerramiento ganadero',
    'proteccion del ganado frente a depredadores',
  ],
  energia_en_explotaciones: [
    'autoconsumo en explotaciones agrarias', 'energia renovable en explotaciones agrarias',
    'eficiencia energetica en explotaciones agrarias', 'fotovoltaica para riego',
    'bombeo solar para riego', 'biogas agroganadero', 'biogas ganadero',
    'biometano agroganadero', 'planta de biogas de purines',
    'biomasa agricola', 'residuo agricola para energia', 'agrivoltaica',
  ],
});

// Acrónimos rurales que también existen con otro significado administrativo.
// Se conservan para títulos y organismos, pero no deciden por aparecer solo en
// el cuerpo: en el BON, "PAC" forma parte de una leyenda tributaria genérica.
const METADATA_ONLY_RURAL_TERMS = Object.freeze(['pac']);

const AI1_STATUS = Object.freeze(['active', 'upcoming', 'closed', 'informational', 'unknown']);
const CONTENT_TYPES = Object.freeze([
  'aid',
  'obligation',
  'opportunity',
  'procedure',
  'warning',
  'information',
]);

const REGION_PROVINCES = Object.freeze({
  andalucia: ['almeria', 'cadiz', 'cordoba', 'granada', 'huelva', 'jaen', 'malaga', 'sevilla'],
  aragon: ['huesca', 'teruel', 'zaragoza'],
  asturias: ['asturias'],
  'principado de asturias': ['asturias'],
  cantabria: ['cantabria'],
  'castilla y leon': ['avila', 'burgos', 'leon', 'palencia', 'salamanca', 'segovia', 'soria', 'valladolid', 'zamora'],
  'castilla-la mancha': ['albacete', 'ciudad real', 'cuenca', 'guadalajara', 'toledo'],
  cataluna: ['barcelona', 'girona', 'gerona', 'lleida', 'lerida', 'tarragona'],
  extremadura: ['badajoz', 'caceres'],
  galicia: ['a coruna', 'la coruna', 'lugo', 'ourense', 'orense', 'pontevedra'],
  'islas baleares': ['illes balears', 'baleares'],
  'illes balears': ['illes balears', 'baleares'],
  baleares: ['illes balears', 'baleares'],
  canarias: ['las palmas', 'santa cruz de tenerife'],
  'la rioja': ['la rioja'],
  madrid: ['madrid'],
  'comunidad de madrid': ['madrid'],
  murcia: ['murcia'],
  'region de murcia': ['murcia'],
  navarra: ['navarra'],
  'comunidad foral de navarra': ['navarra'],
  'pais vasco': ['alava', 'araba', 'bizkaia', 'vizcaya', 'gipuzkoa', 'guipuzcoa'],
  euskadi: ['alava', 'araba', 'bizkaia', 'vizcaya', 'gipuzkoa', 'guipuzcoa'],
  'comunitat valenciana': ['alicante', 'alacant', 'castellon', 'castello', 'valencia'],
  'comunidad valenciana': ['alicante', 'alacant', 'castellon', 'castello', 'valencia'],
  ceuta: ['ceuta'],
  melilla: ['melilla'],
});

function boundedInteger(value, fallback, [min, max]) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.max(min, Math.min(max, Math.floor(parsed)));
}

function normalizeLimits(overrides = {}) {
  return Object.fromEntries(
    Object.entries(DEFAULT_LIMITS).map(([key, fallback]) => [
      key,
      boundedInteger(overrides[key], fallback, LIMIT_BOUNDS[key]),
    ])
  );
}

module.exports = {
  AI1_MODEL,
  AI2_MODEL,
  VERSIONS,
  DEFAULT_LIMITS,
  LIMIT_BOUNDS,
  RURAL_ORGANIZATIONS,
  RURAL_TERMS_BY_TOPIC,
  METADATA_ONLY_RURAL_TERMS,
  AI1_STATUS,
  CONTENT_TYPES,
  REGION_PROVINCES,
  normalizeLimits,
};
