const BOLETINES_PROVINCIALES = [
  {
    codigo: 'botha',
    fuente: 'BOTHA',
    nombre: 'Boletin Oficial del Territorio Historico de Alava',
    comunidad: 'pais_vasco',
    provincia: 'Alava',
    endpoint: '/scrape-botha-oficial',
    estado: 'activo',
    prioridad: 1,
  },
  {
    codigo: 'bob',
    fuente: 'BOB',
    nombre: 'Boletin Oficial de Bizkaia',
    comunidad: 'pais_vasco',
    provincia: 'Bizkaia',
    endpoint: '/scrape-bob-oficial',
    estado: 'pendiente',
    prioridad: 2,
  },
  {
    codigo: 'bog',
    fuente: 'BOG',
    nombre: 'Boletin Oficial de Gipuzkoa',
    comunidad: 'pais_vasco',
    provincia: 'Gipuzkoa',
    endpoint: '/scrape-bog-oficial',
    estado: 'pendiente',
    prioridad: 3,
  },
  {
    codigo: 'bop_las_palmas',
    fuente: 'BOP_LAS_PALMAS',
    nombre: 'Boletin Oficial de la Provincia de Las Palmas',
    comunidad: 'canarias',
    provincia: 'Las Palmas',
    endpoint: '/scrape-bop-las-palmas-oficial',
    estado: 'pendiente',
    prioridad: 4,
  },
  {
    codigo: 'bop_santa_cruz_tenerife',
    fuente: 'BOP_SANTA_CRUZ_TENERIFE',
    nombre: 'Boletin Oficial de la Provincia de Santa Cruz de Tenerife',
    comunidad: 'canarias',
    provincia: 'Santa Cruz de Tenerife',
    endpoint: '/scrape-bop-santa-cruz-tenerife-oficial',
    estado: 'pendiente',
    prioridad: 5,
  },
];

module.exports = { BOLETINES_PROVINCIALES };
